import React from 'react'
import { Box,Typography } from '@mui/material'
export default function Stories() {
  return (
    <Box style={{margin:"80px 20px 50px 20px"}}>
<Typography  style={{fontSize:"1rem",fontWeight:"bold",color:"#606060",marginBottom:"20px"}}>
Top Stories:Brand Directory
</Typography>
<Typography>
<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>MOST SEARCHED FOR ON FLIPKART: </span><a href="/" style={{textDecoration:"none",color:"#979797"}}>Holi Gifts</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Holi Hampers</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Holi Balloons </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Holl Color</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Fresh Flower Delivery </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> iPhone 15 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>iPhone 15 Plus </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> iPhone 15 Pro</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> iPhone 15 Pro Max</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Vivo x 100</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Spoyl Store </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> SAMSUNG Flip5 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> SAMSUNG Folds </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Flipkart Axis Bank Super Flite Credit card </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> 5G Mobile Phones </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Primebook Laptops </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Moto Eige 40</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Grievance Redressal </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> OPPO Renno Pro 5G </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> iPhone 13 Help Centre Track Orders </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Manage Orders Return Orders Gift Later Cards Store Flipkart Axis Bank Credit Card Pay</a> </p>

<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>MOBILES</span> <a href="/" style={{textDecoration:"none",color:"#979797"}}>Samsung Dalaxy S24 50</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Samsung Galaxy 824 50 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> IPhone 12 6408</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Phone 12 Pro 51208 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Phone 12 12808 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Vivo Y15 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> SAMSUNG Galaxy S21 FE SO</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Infinix HOT 301 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Hesime 10 Pro 50 MOTOROLA 062 SG </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Nothing Phone </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> REDMI Note 12 Pro
50 Infinix SMART 7 Vivo Y12 Oppo A12 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Motorola 5g Phone </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Realme 5g Smartphone Appie 5g Phone </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> igoo Sg Phones </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Oneplus Sg Phones </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Vivo 5g Phones </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Oppo 5g Smart Phones Oppo F15 Oppo A31 Samsung A71 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Samsung 451</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Samsung A31 iPhone 11</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> iPhone 11 Pro 4G Mobile Nokia Mobile Samsung Mobile Iphone Oppo Mobile Vivo Mobile</a></p>

<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>CAMERA</span> <a href="/" style={{textDecoration:"none",color:"#979797"}}>GoPro Action Camera </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Nikon Camera Canon Camara Sony Camera </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Canon DSLR NIKON DSLR</a> </p>

<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>LAPTOPS</span><a href="/" style={{textDecoration:"none",color:"#979797"}}> Asus ROG Ally
MacBook Pro M2 Premium Laptop ASUS ROG Strix SCAR 18 (2023) Cure 19 13th Gen ASUS ROG Zephyrus M16 (2023) Care 19 13th Gen </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> ASUS Zenbook 14 OLED (2022) Realme Book Prime Core 15 11th Gen </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Microsoft Surface Go Pentium 128GB </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Apple Laptops</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Acer Laptops</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Lenovo Laptops</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Dell Laptops Asus Laptops</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> HP Laptops </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Gaming Laptops </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>2 in 1 Laptops</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Laptops Dell latest laptops 2022 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>HP latest laptops 2022 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Infinix INBook V1 Plus </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>SAMSUNG Galaxy
Book3</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> 12th Gen Intel Core Laptops</a></p>

<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>TVS</span> <a href="/" style={{textDecoration:"none",color:"#979797"}}>Nokia TV</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Panasonic TV </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Thomson TV </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> MIX Pro </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Realme TV </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Motorola TV </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>OnePlus TVS</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> LG TV </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>TV </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Sony TV </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Samsung TV </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Android Television </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Iffaicon TV </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>MI TV</a></p>

<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>LARGE APPLIANCES:</span><a href="/" style={{textDecoration:"none",color:"#979797"}}> Television </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Washing Machines </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Refrigerators</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Air Conditioners</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Electric Cookers</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Electric Jug</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Heater/Travel Kettles </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Induction Cooktops </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Inverters/stabilizer</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> hons/Iron Bins</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Mixer Grinder </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Juicer </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Wet Grinders</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Chimmerys Microwave Overs </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Vacuum Cleaners</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Water Purifier Fari</a></p>


<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>CLOTHING </span><a href="/" style={{textDecoration:"none",color:"#979797"}}>Green bridal lehenga Tops Shoes Sunglasses </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Bridal Blouse </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Half saree blouse designs </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Designer blouses </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Blouse designs </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Shirts </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Cotton saree blouse designs </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Tshirts </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Jeans </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Sarees </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Dresses </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> One pieces Groom wedding sherwani </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Designer Salwar Suits </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Bra</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Cotton simple blouse designs</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Banarasi saree blouse designs</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Stylish biouse astin design</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Track Pant Blouse neck designs </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Men Kurtas </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Party Dresses Palazzo Suits Anarkali </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Gowns Cut out dress Salwar
Suits Kurtis Designer Sarees Leggings Shorts </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Georgette Sarees Ethnic Wear uppada pattu sarees Blouse back design Jodhour pants</a></p>

<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>FOOTWEAR:</span><a href="/" style={{textDecoration:"none",color:"#979797"}}> Adidas Shoes </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Reebok Shoes</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Nike Shoes </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Puma Shoes </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Boots Bata Shoes </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Woodland Shoes Skechers Shoes Sneakers Womens Boots Sports Shoes </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Loafers Sandals Lotto Sports Shoes Casual Shoes </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Womens Skechers
Shoes Asics Sports Shoes Forma: Shoes School Shoes</a></p>

<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>GROCERIES</span><a href="/" style={{textDecoration:"none",color:"#979797"}}>Phonalle Grocery Voucher </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Hand Wash Soap </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Cashew Nuts </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Sunflower Oil Eggs </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Toilet Cleaner Harpic Tollot Cleaner Dettol Soap </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Mustard Oil Biscuits Cheese Patanjali Atta Fortune Dil Aashirvaad Atta </a></p>


<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>BEST SELLING ON FLIPKART</span>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Headphones </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Best Gas Geyser </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Kitchen Geyser </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Nutri Blenders </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Portable Air Couter </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Best Air Cooler Bags </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Hitachi Refrigerator 3 Door</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Books</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Toys</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Candles </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Helmets </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Wall Clocks </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Baby
Food</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Chocolates </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Cycles</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Calculators </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Lipsticks </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Mask </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Vertiv UPS</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Fastrack Watches</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Wallets </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Earrings </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Gold Coins</a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Realme Pad Mini </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Handtraps conekt SW2 Smartwatch </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Mivi DuoPods 8350 </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>Speaker Cleaner</a></p>

<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>FURNITURE</span>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Furniture Sofas Beds Dining sets </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Wardrobes Mattresses TV Units Tables Chairs </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Shelves </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Dean Bags Office Chairs Computer Table Office Tables Red Sota </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Wakefit Beds </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> White Sofa Wakefit Mattress </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Green Sota Black
Sofa Bruwn Sola</a></p>

<p style={{fontSize:"0.8rem",color:"#979797"}}><span style={{fontSize:"0.9rem",color:"#818181"}}>BGMH:</span>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Whey Protein Homeopathy </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Cricket </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Cycles Footballs Treadmills </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}>
Constmas Gifts Fitness Accessories Online Guitar Books Store Musical Instrument Store Daour Chyawanprash </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Baidyanath Chyawanprash </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Energy Drinks Toys Milk Drink Mixes Rakhi </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Chyawanprash </a>|<a href="/" style={{textDecoration:"none",color:"#979797"}}> Indian Fag Protein Supplements</a></p>


</Typography>

    </Box>
  )
}
